#
#  Configuration for vcard
#

gulp:
  watch:
    js:
      - ./modules/*/js/*.js
    jsdoc:
#      - ./*.js
#      - ./gulp/**/*.js
      - ./lib/**/*.js
#      - ./modules/**/*.js
#      - ./src/**/*.js
    jshint:
      - ./*.js
      - ./gulp/**/*.js
      - ./lib/**/*.js
      - ./modules/**/*.js
      - ./src/**/*.js
    jsonlint:
      - ./**/*.json
      - ./.jscsrc
      - ./.jshintrc
      - ./.lesshintrc
    lesshint:
      - ./src/less/**/*.less
    yamllint:
      - ./**/*.yaml
      - ./**/*.yml
    ejslint:
      - ./**/*.ejs
    less:
      - ./src/less/app.less
      - ./src/less/**/*.less
      - ./modules/**/*.less
    puglint:
      - ./**/*.pug
    test-vcards:
      - ./modules/vcards/*.*
      - ./modules/vcards/tests/*.*
      - ./modules/vcards/views/*.*
      - ./htdocs/css/app.css
    webserver:
      - ./server.js
      - ./modules/vcards/*.js
    livereload:
      - ./htdocs/**/*.html
      - ./modules/**/*.ejs
      - ./modules/**/*.pug
      - ./htdocs/img/**/*.*
      - ./htdocs/css/app.css
      - ./htdocs/js/**/*.js
  tests:
    vcards:
      - ./modules/vcards/tests/*.js
  build:
    jsdoc:
      src:
        - ./*.js
        - ./gulp/**/*.js
        - ./lib/**/*.js
        - ./modules/**/*.js
        - ./src/**/*.js
      dest: ./docs/jsdoc
    js:
      src: ./modules/*/js/*.js
      dest: ./htdocs/js
      replace:
        '/js': ''
    less:
      src: ./src/less/app.less
      dest: ./htdocs/css

webserver:
  server: ./server.js
  docroot: ./htdocs
  modules: ./modules
  routes:
    - ./modules/**/routes.js
  httpPort: 8080
  livereloadPort: 8081
  verbose: false
