#
#  Configuration for vcard webserver
#

paths:
  watch:
    jshint:
      - './*.js'
      - './gulp/**/*.js'
      - './lib/**/*.js'
      - './modules/**/*.js'
      - './src/**/*.js'
    jsonlint:
      - './**/*.json'
      - './.jscsrc'
      - './.jshintrc'
      - './.lesshintrc'
    lesshint:
      - './src/less/**/*.less'
    yamllint:
      - './**/*.yaml'
      - './**/*.yml'
    ejslint:
      - './**/*.ejs'
    less:
      - './src/less/app.less'
      - './src/less/**/*.less'
    'webserver:restart':
      - './server.js'
      - './gulp/server.js'
    'webserver:livereload':
      - './htdocs/**/*.html'
#      - './htdocs/views/**/*.ejs'
#      - './htdocs/img/**/*.*'
      - './htdocs/css/app.css'
  build:
    less:
      src: './src/less/app.less'
      dest: './htdocs/css'

webserver:
  server: './server.js'
  docroot: './htdocs'
  modules: './modules'
  httpPort: 8080
  livereloadPort: 8081
