#
#  Configuration for vcard
#

gulp:
  watch:
    jsdoc:
#      - ./*.js
#      - ./gulp/**/*.js
      - ./lib/**/*.js
#      - ./modules/**/*.js
#      - ./src/**/*.js
    jshint:
      - ./*.js
      - ./gulp/**/*.js
      - ./lib/**/*.js
      - ./modules/**/*.js
      - ./src/**/*.js
    jsonlint:
      - ./**/*.json
      - ./.jscsrc
      - ./.jshintrc
      - ./.lesshintrc
    lesshint:
      - ./src/less/**/*.less
    yamllint:
      - ./**/*.yaml
      - ./**/*.yml
    ejslint:
      - ./**/*.ejs
    less:
      - ./src/less/app.less
      - ./src/less/**/*.less
    test-mocha:
      - ./modules/vcard/tests/model/*.*
      - ./modules/vcard/model/*.js
    webserver:
      - ./server.js
    livereload:
      - ./htdocs/**/*.xhtml
      - ./modules/**/*.ejs
#      - ./htdocs/img/**/*.*
      - ./htdocs/css/app.css
  tests:
    mocha:
      vcard: ./modules/vcard/tests/model/index.js
  build:
    jsdoc:
      src:
      - ./*.js
      - ./gulp/**/*.js
      - ./lib/**/*.js
      - ./modules/**/*.js
      - ./src/**/*.js
      dest: ./docs/jsdoc
    less:
      src: ./src/less/app.less
      dest: ./htdocs/css

webserver:
  server: ./server.js
  docroot: ./htdocs
  modules: ./modules
  httpPort: 8080
  livereloadPort: 8081
