version: '2'

services:
  webserver:
    container_name: webserver
    image: uwegerdes/vcard
    volumes:
    - .:/home/node/app

  vcard-compare-layouts:
    container_name: vcard-compare-layouts
    image: uwegerdes/compare-layouts
    links:
      - webserver
    volumes:
     - ./tests/dev/compare-layouts:/home/node/app/config

