version: '2'

services:
  webserver:
    build:
      context: .
    container_name: vcard-dev
    hostname: vcard-dev
    image: uwegerdes/vcard
    networks:
      vcard-bridge:
        ipv4_address: 172.25.0.2
    ports:
      - '8080'
    volumes:
    - .:/home/node/app
#    command: gulp --silent
    command: npm run dev

  compare-layouts:
    build:
      context: ../../docker-compare-layouts
    container_name: vcard-compare-layouts
    hostname: vcard-compare-layouts
    image: uwegerdes/compare-layouts
#    links:
#      - webserver
    networks:
      vcard-bridge:
        ipv4_address: 172.25.0.3
    ports:
      - '8080'
    volumes:
     - ../../docker-compare-layouts:/home/node/app
     - ./tests/dev/compare-layouts:/home/node/app/config
     - ./modules:/home/node/app/config/modules
#    command: gulp --silent
    command: npm run dev

networks:
  vcard-bridge:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1
