version: '3.5'

services:
  vcards-dev:
    build:
      context: .
    container_name: vcards-dev
    hostname: vcards-dev
    image: uwegerdes/vcards
    environment:
      - NODE_ENV=development
    networks:
      - vcards-bridge
    ports:
      - 51280:8080
      - 51281:8081
    volumes:
    - .:/home/node/app
#    command: gulp --silent
    command: npm run dev

  vcards-e2e:
    build:
      context: .
    container_name: vcards-e2e
    hostname: vcards-e2e
    image: uwegerdes/vcards
    environment:
      - NODE_ENV=production
    networks:
      - vcards-bridge
    ports:
      - 51285:8080
      - 51286:8081
    volumes:
    - .:/home/node/app
#    command: gulp --silent
    command: npm run dev

networks:
  vcards-bridge:
    driver: bridge
    name: vcards-bridge
