version: '2'

services:
  vcard-compare-layouts:
    image: uwegerdes/compare-layouts
    environment:
     - NODE_ENV=development
    volumes:
     - ./tests/compare-layouts:/home/node/app/config

  db:
    image: mongo
    volumes:
      - /srv/docker/meanjs/vcard:/data/db

