version: '3.5'

services:
  vcards-dev:
    build:
      context: .
    container_name: vcards-dev
    hostname: vcards-dev
    image: uwegerdes/vcards
    environment:
      - NODE_ENV=development
    ports:
      - 51280:8080
      - 51281:8081
      - 51283:8443
    volumes:
    - ./modules/vcards:/home/node/app/modules/vcards
    - ./coverage:/home/node/app/coverage
    - ./key:/home/node/app/docs
    - ./fixture:/home/node/app/fixture
    - ./key:/home/node/app/key
#    command: gulp --silent
    command: npm run dev
