version: '3.5'

services:
  vcards-dev:
    build:
      context: .
    container_name: vcards-dev
    hostname: vcards-dev
    image: uwegerdes/vcards
    environment:
      - NODE_ENV=development
    ports:
      - 51280:8080
      - 51281:8081
    volumes:
    - .:/home/node/app
#    command: gulp --silent
    command: npm run dev

  vcards-prod:
    build:
      context: .
    container_name: vcards-prod
    hostname: vcards-prod
    image: uwegerdes/vcards
    environment:
      - NODE_ENV=production
    ports:
      - 51282:8080
      - 51283:8081
    volumes:
    - .:/home/node/app
#    command: gulp --silent
    command: npm run dev
