version: '3.5'

services:
  vcards-dev:
    build:
      context: .
    container_name: vcards-dev
    hostname: vcards-dev
    image: uwegerdes/vcards
    networks:
      - vcards-bridge
    ports:
      - 51280:8080
      - 51281:8081
    volumes:
    - .:/home/node/app
#    command: gulp --silent
    command: npm run dev

networks:
  vcards-bridge:
    driver: bridge
    name: vcards-bridge
