version: '2'
services:
  webserver:
    build: ./webserver/
    ports:
     - "3146:80"
     - "3147:35729"
    environment:
     - NODE_ENV=development
     - DB_1_PORT_27017_TCP_ADDR=db
    depends_on:
     - db
    volumes:
     - ./:/home/node/app

  db:
    image: mongo
    volumes:
      - /srv/docker/meanjs/vcard:/data/db
